# .swiftlint.yml - Упрощенная версия для начального этапа
# Конфигурация SwiftLint для проекта Tochka

# Директории для анализа
included:
  - Tochka
  - Modules

# Исключенные директории
excluded:
  - Derived
  - .build
  - vendor
  - Carthage
  - Tests/LinuxMain.swift

# Отключенные правила (временно для начала разработки)
disabled_rules:
  - file_header                    # Заголовки файлов - добавим позже
  - trailing_whitespace
  - line_length
  - function_default_parameter_at_end  # Параметры по умолчанию
  - opening_brace                 # Пробелы перед скобками
  - prefixed_toplevel_constant    # Префиксы констант
  - trailing_comma               # Запятые в конце
  - number_separator            # Разделители в числах
  - type_name                   # Ограничения на имена типов
  - mark_comment               # MARK комментарии
  - no_print                   # Использование print()
  - todo                       # TODO комментарии
  - multiple_closures_with_trailing_closure  # Множественные замыкания

# Минимальные opt-in правила (только самые важные)
opt_in_rules:
  - empty_count
  - force_unwrapping

# Настройки для оставшихся правил
line_length:
  warning: 200
  error: 300
  ignores_urls: true
  ignores_comments: true

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 800
  error: 1200

identifier_name:
  min_length: 1  # Разрешаем короткие имена
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - z
    - i
    - j

# Настройка отступов
indentation: 4

# Только критичные кастомные правила
custom_rules: {}

# Режим анализа - только warnings, не errors
reporter: "xcode"

# Строгость - только warning для большинства правил
strict: false
